### PR TITLE
Remove enum34 dependency

### PR DESCRIPTION
**Pull request by balloob**
Description in the README states that only Python 3.4+ are supported.

Enum34 is a backport of the Enum package from Python 3.4 to older versions:

> Python 3.4 Enum backported to 3.3, 3.2, 3.1, 2.7, 2.6, 2.5, and 2.4

And thus it can be removed.

When a new release is done, please update the version in Home Assistant too 👍  We're soon going to block all packages that depend on enum34.

### CODE REVIEW

**Comment by CharlesBlonde** [comment]
Hi @balloob,

I think you are right. It was a legacy dependency because I planned to port the library to Python 2.7 but in fact I dropped this support.

I'll do some tests in order to validate everything is all right, publish a new release and upgrade version in HA.

**Comment by balloob** [comment]
Thanks!

**Comment by balloob** [comment]
If you want to support older Pythons in the future, depend on `enum-compat` and it will only install `enum34` on Python versions that need it.

**Comment by CharlesBlonde** [comment]
Thanks for the PR.
Before releasing a new version and submitting a PR in HA, I have 2 issues I would like to fix:
* https://github.com/home-assistant/home-assistant/issues/8569
* https://github.com/home-assistant/home-assistant/issues/8798

For the first one I know how to fix it but not yet the second one

**Comment by balloob** [comment]
I'll update it then in my PR. enum34 is breaking other components for our users.

**Comment by balloob** [comment]
:/ it's not a simple upgrade, it requires changes to the platforms. I'll leave it up to you.

Dyson will be disabled by next release if platform is not upgraded to the latest version.

**Comment by CharlesBlonde** [comment]
I'll do it this week-end. It should be OK for HA next release.
And yes, there is a small change to do in the platform but I already have a branch (not pushed) with the changes.

**Comment by balloob** [comment]
Why wait pushing changes out if you already have some fixes ready?

**Comment by CharlesBlonde** [comment]
Because I haven't done all the tests I wanted to do.
At this time, it's just prevent issue https://github.com/home-assistant/home-assistant/issues/8569 from happening by setting humidity value to 0 instead of failing but I think the best solution is to return NA => tests must be updated.
The main part is done but not the finishes.

**Comment by CharlesBlonde** [comment]
I just submitted the PR https://github.com/home-assistant/home-assistant/pull/8826

Tests should pass and it will remove enum34 dependency (from libpurecoollink)

**Pull request merged**
